export const OPTION = [
  {
    id: "regions",
    label: "Regions",
    icon: "Map",
    description: "Browse top ski regions across Europe, Asia & North America",
    href: "/regions",
    formFields: ["destination", "dates", "guests"],
  },
  {
    id: "lodging",
    label: "Lodging",
    icon: "Building2",
    description: "Luxury chalets, slope-side hotels & private residences",
    href: "/lodging",
    formFields: ["destination", "checkin", "checkout", "guests"],
  },
  {
    id: "resorts",
    label: "Resorts",
    icon: "Mountain",
    description: "20+ world-class resorts from Niseko to Zermatt",
    href: "/resorts",
    formFields: ["resort", "dates", "guests"],
  },
  {
    id: "passes",
    label: "Passes",
    icon: "Ticket",
    description: "Flexible lift passes tailored to your schedule & budget",
    href: "/passes",
    formFields: ["resort", "duration", "guests"],
  },
];

export const DESTINATIONS = [
  {
    id: "niseko",
    name: "Niseko",
    country: "Japan",
    region: "Hokkaido, Japan",
    continent: "Asia",
    flag: "🇯🇵",
    tagline: "Legendary powder snow",
    altitude: "1,308m",
    season: "Dec – Mar",
    icon: "Trophy",
    badge: " Top rated",
    tags: ["1,308m", "Dec – Mar", "Powder"],
    price: "$1,200",
    image: "/images/niseko.jpg",
    href: "#contact",
  },
  {
    id: "chamonix",
    name: "Chamonix",
    country: "France",
    region: "Haute-Savoie, France",
    continent: "Europa",
    flag: "🇫🇷",
    tagline: "Mont Blanc & expert runs",
    altitude: "3,842m",
    season: "Dec – Apr",
    icon: "TrendingUp",
    badge: " Expert runs",
    tags: ["3,842m", "Dec – Apr", "Expert"],
    price: "$980",
    image: "/images/chamonix.jpg",
    href: "#contact",
  },
  {
    id: "zermatt",
    name: "Zermatt",
    country: "Switzerland",
    region: "Valais, Switzerland",
    continent: "Europa",
    flag: "🇨🇭",
    tagline: "Car-free alpine luxury",
    altitude: "3,883m",
    season: "Nov – Apr",
    icon: "Gem",
    badge: " Luxury",
    tags: ["3,883m", "Nov – Apr", "Luxury"],
    price: "$1,450",
    image: "/images/zermatt.jpg",
    href: "#contact",
  },
  {
    id: "whistler",
    name: "Whistler",
    country: "Canada",
    region: "British Columbia, Canada",
    continent: "North America",
    flag: "🇨🇦",
    tagline: "North America's largest resort",
    altitude: "2,284m",
    season: "Nov – May",
    // icon: "Trophy",
    // badge: " Top rated",
    tags: ["2,284m", "Nov – May", "Vast Terrain"],
    price: "$1,100",
    image: "/images/whistler.jpg",
    href: "#contact",
  },
  {
    id: "aspen",
    name: "Aspen",
    country: "USA",
    region: "Colorado, USA",
    continent: "North America",
    flag: "🇺🇸",
    tagline: "World-class skiing & nightlife",
    altitude: "3,813m",
    season: "Dec – Apr",
    // icon: "Gem",
    // badge: " Luxury",
    tags: ["3,813m", "Dec – Apr", "Apres-Ski"],
    price: "$1,600",
    image: "/images/aspen.jpg",
    href: "#contact",
  },
  {
    id: "st-moritz",
    name: "St. Moritz",
    country: "Switzerland",
    region: "Graubünden, Switzerland",
    continent: "Europa",
    flag: "🇨🇭",
    tagline: "Birthplace of winter tourism",
    altitude: "3,303m",
    season: "Dec – Apr",
    // icon: "Gem",
    // badge: " Luxury",
    tags: ["3,303m", "Dec – Apr", "Elegant"],
    price: "$1,750",
    image: "/images/st-moritz.jpg",
    href: "#contact",
  },
  {
    id: "cortina",
    name: "Cortina",
    country: "Italy",
    region: "Dolomites, Italy",
    continent: "Europa",
    flag: "🇮🇹",
    tagline: "Queen of the Dolomites",
    altitude: "2,924m",
    season: "Dec – Apr",
    // icon: "TrendingUp",
    // badge: " Top views",
    tags: ["2,924m", "Dec – Apr", "Dolomites"],
    price: "$1,050",
    image: "/images/cortina.jpg",
    href: "#contact",
  },
  {
    id: "banff",
    name: "Banff",
    country: "Canada",
    region: "Alberta, Canada",
    continent: "North America",
    flag: "🇨🇦",
    tagline: "Stunning national park skiing",
    altitude: "2,730m",
    season: "Nov – May",
    // icon: "Trophy",
    // badge: " Top rated",
    tags: ["2,730m", "Nov – May", "Nature"],
    price: "$950",
    image: "/images/banff.jpg",
    href: "#contact",
  },
  {
    id: "rusutsu",
    name: "Rusutsu",
    country: "Japan",
    region: "Hokkaido, Japan",
    continent: "Asia",
    flag: "🇯🇵",
    tagline: "The best tree run skiing",
    altitude: "994m",
    season: "Dec – Apr",
    // icon: "Trophy",
    // badge: " Top rated",
    tags: ["994m", "Dec – Apr", "Powder"],
    price: "$1,350",
    image: "/images/rusutsu.jpg",
    href: "#contact",
  },
  {
    id: "hakuba",
    name: "Hakuba",
    country: "Japan",
    region: "Nagano, Japan",
    continent: "Asia",
    flag: "🇯🇵",
    tagline: "Olympic level terrain",
    altitude: "1,831m",
    season: "Dec – Apr",
    // icon: "TrendingUp",
    // badge: " Expert runs",
    tags: ["1,831m", "Dec – Apr", "Expert"],
    price: "$1,100",
    image: "/images/hakuba.jpg",
    href: "#contact",
  },
  {
    id: "yongpyong",
    name: "Yongpyong",
    country: "South Korea",
    region: "Pyeongchang, South Korea",
    continent: "Asia",
    flag: "🇰🇷",
    tagline: "Famous winter destination",
    altitude: "1,438m",
    season: "Nov – Mar",
    // icon: "Gem",
    // badge: " Luxury",
    tags: ["1,438m", "Nov – Mar", "Family"],
    price: "$850",
    image: "/images/yongpyong.jpg",
    href: "#contact",
  },
];

export const THEARTIC = [
  {
    id: "expert",
    icon: "Compass",
    title: "Expert Knowledge",
    tagline:
      "Our team has skied the runs and slept in the beds. We offer genuine, first-hand advice.",
  },
  {
    id: "tailored",
    icon: "Gem",
    title: "Tailored Experiences",
    tagline:
      "From family-friendly bunny hills to extreme heli-skiing, we build trips around your needs.",
  },
  {
    id: "support",
    icon: "Headset",
    title: "24/7 Support",
    tagline:
      "Weather changes, plans shift. We're here around the clock to ensure your trip runs smoothly.",
  },
];

export const NAV_LINKS = [
  { label: "Destinations", href: "/destinations" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/#contact" },
];

export const MEET = [
  {
    id: "sehan-jengkins",
    title: "Sehan Jengkins",
    jobs: "Founder & CEO",
    caption: "Favorite resort: Chamonix",
    image: "/images/sehan.jpg",
  },
  {
    id: "marcus-berg",
    title: "Marcus Berg",
    jobs: "Head of Destinations",
    caption: "Favorite resort: Niseko",
    image: "/images/marcus.jpg",
  },
  {
    id: "elena-rostova",
    title: "Elena Rostova",
    jobs: "Luxury Concierge",
    caption: "Favorite resort: Zermatt",
    image: "/images/elena.jpg",
  },
  {
    id: "david-chen",
    title: "David Chen",
    jobs: "Operations Manager",
    caption: "Favorite resort: Whistler",
    image: "/images/david.jpg",
  },
];
